### PR TITLE
Fhir 1.8 Update

### PR DESCRIPTION
**Pull request by cjduffett**
Updated the intervention-engine/fhir server dependency to FHIR 1.8. Also updated the index file and capability statement to match those of the new FHIR 1.8 server. I built the server and tested it out with some basic routes. Everything checks out.

### CODE REVIEW

**Comment by gregquinn2001** [comment]
Can't merge this in until we have syntheticmass site and bulk loader updated and all tested and ready to go

**Comment by cjduffett** [comment]
I don't see why not. I really don't want to deploy it on SyntheticMass until this PR is merged. I figured we would start rolling things out on dev (which yes, will be broken for a bit), get everything stable, then migrate it through stage into production.

As far as this repository and code base is concerned, this PR is up-to-date and working.

**Comment by gregquinn2001** [comment]
We can have branches in each repository for the update to FHIR 1.8. Once all of them are working sm-dev, then we can merge them all into master and deploy to stage from master. If it works on stage, then we deploy to production. Make sense? I don't want the master branch to be out of sync with the other components. We are taking a similar approach with all the tool repositories

**Comment by cjduffett** [comment]
I think you and I are in agreement - that's why I'm asking to merge this with the `stu3_jan2017` branch, not `master`. If you want to maintain different versions of this GoFHIR server as well (that mirror the intervention-engine/fhir repo) then we can do that.

**Comment by gregquinn2001** [comment]
Yeah. I think I mis-spoke. stu3_jan2017 is basically the "master" for syntheticmass.  In other words, that's our production version

**Pull request merged**
